---
services:

  broker01:
    image: confluentinc/cp-server:7.8.0
    hostname: broker01
    container_name: broker01
    ports:
      - "9092:9092"
      - "9101:9101"
    env_file:
      - .env.kafka01
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 30s
      retries: 5
    networks:
      - net-corso-apache

  broker02:
    image: confluentinc/cp-server:7.8.0
    hostname: broker02
    container_name: broker02
    ports:
      - "9093:9093"
      - "9102:9101"
    env_file:
      - .env.kafka02    
    healthcheck:
      test: nc -z localhost 9093 || exit 1
      interval: 30s
      retries: 5
    networks:
      - net-corso-apache

  broker03:
    image: confluentinc/cp-server:7.8.0
    hostname: broker03
    container_name: broker03
    ports:
      - "9094:9094"
      - "9103:9101"
    env_file:
      - .env.kafka02
    healthcheck:
      test: nc -z localhost 9094 || exit 1
      interval: 30s
      retries: 5
    networks:
      - net-corso-apache
  

#  kafka-ui:
#    image: provectuslabs/kafka-ui
#    hostname: kafka-ui
#    container_name: kafka-ui
#    ports:
#    - "9088:8080"
#    environment:
#      DYNAMIC_CONFIG_ENABLED: "true"
  
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.8.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker01
      - broker02
      - broker03
    ports:
      - "9021:9021"
    env_file:
      - .env.controlcenter
    networks:
      - net-corso-apache

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"  # interfaccia web del master
      - "7077:7077"  # porta per le comunicazioni Spark
    networks:
      - net-corso-apache

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"  # interfaccia web del worker  
    networks:
      - net-corso-apache

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8082:8081"  # interfaccia web del worker  
    networks:
      - net-corso-apache

networks:
  net-corso-apache:
    # name: net-corso-apache  # stesso nome esplicito
    driver: bridge      

